name: Run unit tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show folder structure
        run: ls -R

      - name: Run Maven tests
        run: mvn -f AskWebTesting/AskTesting/pom.xml test
